# Generated by Django 3.2.6 on 2021-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incubation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Address', models.CharField(max_length=1000)),
                ('City', models.CharField(max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=250)),
                ('Company_Name', models.CharField(max_length=250)),
                ('Company_Logo', models.ImageField(upload_to='pics')),
                ('Company_Description', models.TextField(max_length=2500)),
                ('Problem_Description', models.TextField(max_length=2500)),
                ('Solution_Description', models.TextField(max_length=2500)),
                ('Proposition_Description', models.TextField(max_length=2500)),
                ('Competitors_Description', models.TextField(max_length=2500)),
                ('Revenue_Model', models.TextField(max_length=2500)),
                ('Potential_Market_Size', models.TextField(max_length=2500)),
                ('Team_Description', models.TextField(max_length=2500)),
                ('Marketting_Plan', models.TextField(max_length=2500)),
                ('Incubation_Type', models.CharField(max_length=100)),
                ('Business_Proposal', models.TextField(max_length=2500)),
            ],
        ),
    ]
